### ISSUE TITLE
QUESTION ONLY: Full integration with the Marketing API?

### ISSUE THREAD

**Issue by nickbluestone98** [nikolajlovenhardt/laravel-facebook-ads#3]
Hello,

Just wondering if this package you made allows full functionality of the Facebook Marketing API: https://developers.facebook.com/docs/marketing-apis 

Would be a amazing if you could get straight back to me!

Kind Regards,

Nick.

**Comment by nikolajlovenhardt** [comment]
Hi Nick,

This package allows full access to all functionality from the Facebook Marketing API provided you have an access token with the necessary access level.

Nikolaj

**Comment by nickbluestone98** [comment]
Hello @nikolajlovenhardt 

Thanks ever so much for the quick feedback and clarification.

I will look forward to using your package 👍 

Kind Regards,

Nick.
