### ISSUE TITLE
(#2635) You are calling a deprecated version of the Ads API. 

### ISSUE THREAD

**Issue by nickbluestone98** [nikolajlovenhardt/laravel-facebook-ads#4]
Hello,

I am trying to do a basic call to get the ads of the account but get this error:

**(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.9.**

I can create an instance perfectly :D but get stuck with trying to retrieve the ads :( Code below:

```
namespace App\Http\Controllers\FacebookMarketing;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use LaravelFacebookAds\Services\FacebookAdsService;
use LaravelFacebookAds\Clients\Facebook;

class FacebookController extends Controller
{
    /** @var FacebookAdsService */
    protected $facebookAdsService;

    public function __construct(FacebookAdsService $facebookAdsService, Facebook $facebookClient)
    {
        $this->facebookAdsService = $facebookAdsService;
        $this->facebookClient = $facebookClient;
    }

    /**
     * Show ads
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
    	$instance = $this->facebookAdsService->instance();

    	print_r($instance);//woo works! got my instance :D

    	$client = $this->facebookClient;
        $accountId = 'act_1234567890';
        dd($client->account($accountId)->ads()); //#2635 error :(
    }

}
```

**Comment by nikolajlovenhardt** [comment]
Hi @nickbluestone98 

Please try to update to version 1.0.3

**Comment by nickbluestone98** [comment]
Hello, thanks for your response. 

- Updated your lib to `1.0.3`
- My composer.lock facebook api version `2.10.1`

No deprecation error now! thanks! Woo!

I am getting a `AuthorizationException Unsupported get request. in RequestException.php (line 144)` The account ID I am using has admin access and the Ads API Access Level:development.

Is this something at my end or an issue with the API?

Regards,

Nick.

**Comment by nikolajlovenhardt** [comment]
@nickbluestone98 

Did you follow the instructions on generating an api token?

**Comment by nickbluestone98** [comment]
@nikolajlovenhardt , 

I did the generation of everything through the Marketing Facebook API menu with the `QuickStart` instead of your method. I am now getting a response object, thanks for all your help 👍 .

I need to work out how to pull data for a specific business page through the API, if you can advise that would be great.

My response object looks like this

```
array:2 [▼
  "data" => array:1 [▼
    0 => array:10 [▼
      "frequency" => "0"
      "impressions" => "200"
      "reach" => "0"
      "social_impressions" => "200"
      "social_reach" => "0"
      "spend" => "20"
      "total_actions" => "0"
      "total_unique_actions" => "0"
      "date_start" => "2017-09-10"
      "date_stop" => "2017-10-09"
    ]
  ]
  "paging" => array:1 [▼
    "cursors" => array:2 [▼
      "before" => "MAZDZD"
      "after" => "MAZDZD"
    ]
  ]
]
```

My code:

```
    public function index()
    {
    	$instance = $this->facebookAdsService->instance();

    	//dd($instance);//woo works! got my instance :D

    	$client = $this->facebookClient;

        $accountId = 'act_123445566721';

        $fields = array(
		  'frequency',
		  'impressions',
		  'reach',
		  'social_impressions',
		  'social_reach',
		  'spend',
		  'total_actions',
		  'total_unique_actions',
		);

        dd( $client->account($accountId)->getAccount()->getInsights($fields )->getResponse()->getContent() );

    }
```

I really need to link that to a specific business page, when I try get the ads the data array is empty.

Nick.

**Comment by nikolajlovenhardt** [comment]
Hi @nickbluestone98 
Did you manage to figure it out? Sorry for the delayed response
